package com.bookmyshow.enums;

public enum ErrorCode {
    RESOURCE_NOT_FOUND, 
    ILLEGAL_STATE_EXCEPTION,
    USER_NOT_FOUND,
    EMAIL_ALREADY_EXISTS,
    USER_ALREADY_EXISTS,
    VALIDATION_FAILED,
    TOKEN_EXPIRED,
    INVALID_TOKEN,
    UNAUTHORIZED, 
    AUTHENTICATION_FAILED,
    SEAT_LOCK_TIMEOUT,
    INTERNAL_ERROR
}
